version: '3.3'
services:
  github-api-client:
    container_name: "${CONTAINER_NAME}"
    restart: always
    healthcheck:
      test: "curl --fail --silent localhost:${LOCAL_PORT}/api/v3/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 40s
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:${TAG}"
    ports:
      - "${LOCAL_PORT}:${CONTAINER_PORT}"