version: '3.3'
services:
  github-api-client:
    container_name: github-client-api
    restart: always
    healthcheck:
      test: "curl --fail --silent localhost:8080/api/v3/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 40s
    image: "erasmolpa/github-client:1.2.0"
    ports:
      - 8080:8080