spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  servlet:
    context-path: /api/v3


logging:
  level:
    httpclient:
      wire: DEBUG
    org:
      apache:
        http: DEBUG

github_api:
  uri: https://api.github.com/
  search_users_path: search/users?
  version_spec: application/vnd.github.v3+json

management.health.ratelimiters.enabled: true
###                RATE LIMIT
### In Our case, the RATE Limit is restricted by Search api restrictions.
###     https://docs.github.com/en/rest/reference/search#rate-limit
###    https://resilience4j.readme.io/docs/ratelimiter
##    Limit 10 requests per minute without Auth
resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: true
      limitForPeriod: 10
      limitRefreshPeriod: 60s
      timeoutDuration: 0
      eventConsumerBufferSize: 100
  instances:
    githubService:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      registerHealthIndicator: true
      cancelRunningFuture: false
      timeoutDuration: 2s
  instances:
    githubService:
      baseConfig: default

### Actuator Endpoints
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
## Metrics
management:
  endpoint:
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
